# Generated by Django 2.1.8 on 2019-05-24 21:07

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import pypackage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name')),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checksum', models.CharField(max_length=128)),
                ('checksum_type', models.CharField(max_length=8)),
                ('local_file', models.FileField(blank=True, upload_to=pypackage.models.package_local_path)),
                ('remote_path', models.CharField(max_length=256)),
                ('mirrored', models.BooleanField()),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pypackage.Package')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
        ),
    ]
