# Generated by Django 2.1.8 on 2019-05-24 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pypackage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='archive_format',
            field=models.CharField(default='tar.gz', max_length=8),
            preserve_default=False,
        ),
    ]
