# Generated by Django 2.1.8 on 2019-05-24 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pypackage', '0002_version_archive_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='remote_path',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
