# Generated by Django 2.1.8 on 2019-05-25 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pypackage', '0004_auto_20190525_0032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='version',
            old_name='remote_path',
            new_name='mirror_path',
        ),
    ]
